### ISSUE TITLE
I keep getting "We've found 0 distros" with my results.

### ISSUE THREAD

**Issue by NylaTheWolf** [zkldi/homepage#6]
I swear I've gotten results just a week ago with [these answers](https://zkldi.xyz/playground/distro/?q=6&answers=1100101P)!

**Desktop Environment:** GNOME, KDE Plasma.
**Specialist Workflows:** Gaming, Creative Stuff.
**Release Type:** Point Release.

More specifically for workflows, I answers:
1. Lots of gaming
2. Some programming
3. Creative stuff
4. General work

Note that I've gotten this result even without hitting creative stuff. I've noticed that when I go back to the workflows question after getting my results, the general work and programming options are unselected. Gaming and creative stuff remains checked.

I've ran into this problem both when I hit "Let's go!" and when I've hit "Skip the intro!"

I've started getting this issue on my iPad on Safari but I've just tried it on a Chromium browser (Vivaldi) on my Mac and I got the same issue.

But this has worked for me when I used it just a week or two ago. I would get Ubuntu and I think Mint and it'd take me to the instructions on how to set those up.

ETA: I do get results if I choose a rolling release rather than a point release.

**Comment by zkldi** [comment]
Hi! thanks for such a detailed bug report. I had no idea anyone used this tool still.

This is because when you pick "lots of gaming" it attempts to pick distros that have specifically put a decent amount of effort into gaming -- I think it restricts to **just** `manjaro` and `popOS`, except that popOS isn't on the page anymore.

This means that if you pick point release & lots of gaming, you get nothing no matter what.

I should probably re-add popOS to the list of distros.

**Comment by zkldi** [comment]
Fixed. will be live in 5 minutes or so.
